"""Example: run the 6-DoF model and render plots + 3D animation."""

from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np

from minos.sim.runners import simulate_model
from minos.utilities.graphs import PlotKey, plot_selected_parameters
from minos.utilities.visual_3D import visualize_parafoil_pose


def main() -> None:
    # -----------------------------
    # 1) Simulation timeline setup
    # -----------------------------
    # Fixed-step simulation from t=0 to end_time.
    dt = 0.1
    end_time = 15.0
    time_vector = np.linspace(0.0, end_time, int(end_time / dt))

    # ------------------------------------------------------
    # 2) Initial physics state and model parameter overrides
    # ------------------------------------------------------
    # State format:
    # [position_body_NED, velocity_body, euler_angles, angular_velocity]
    initial_conditions = [
        np.array([0.0, 0.0, 0.0]),
        np.array([10.0, 0.0, 3.0]),
        np.array([0.0, 0.0, 0.0]),
        np.array([0.0, 0.0, 0.0]),
    ]
    # Deployment position in inertial/world coordinates.
    params = {"initial_pos": [0.0, 0.0, 400.0]}
    wind = np.array([0.5, 0.0, 0.0])

    # --------------------------------------------------------
    # 3) Build simple control/wind input schedules over time
    # --------------------------------------------------------
    # left/right are flap deflection commands [rad].
    left = np.zeros_like(time_vector)
    right = np.zeros_like(time_vector)
    left[20:60] = 0.2
    right[80:120] = 0.3
    # Keep wind constant for the whole simulation.
    wind_series = [wind.copy() for _ in range(time_vector.size)]
    inputs = [left, right, wind_series]

    # ------------------------------------
    # 4) Run simulation with typed outputs
    # ------------------------------------
    # `snapshots` contains rich per-step diagnostics and state.
    snapshots, _ = simulate_model(time_vector, initial_conditions, inputs, params, inertial=True)

    # ------------------------------------------
    # 5) Create selected timeseries/3D trajectory
    # ------------------------------------------
    # Returns matplotlib figures; we show them below.
    plot_selected_parameters(
        snapshots,
        {PlotKey.VELOCITY, PlotKey.EULER_ANGLES, PlotKey.DEFLECTION, PlotKey.INERTIAL_POSITION_3D},
    )

    # -------------------------------------------------
    # 6) Extract channels for the interactive 3D viewer
    # -------------------------------------------------
    eulers = np.array([s.state.eulers for s in snapshots])
    # Use model NED position states for the viewer input.
    ned_positions = np.array([s.state.position for s in snapshots])

    # Show 3D animation window.
    # - angle_unit="rad" because model state stores radians.
    # - frame="NED" displays North/East/Down axes.
    #   You can switch to frame="ENU" to view East/North/Up.
    visualize_parafoil_pose(
        euler_series=eulers,
        position_series=ned_positions,
        angle_unit="rad",
        frame="NED",
        show=True,
    )
    # Show static plots generated by plot_selected_parameters.
    plt.show()
    plt.close("all")
    print("Example completed successfully.")


if __name__ == "__main__":
    main()
